export default {
  pages: [
    'pages/index/index',
    'pages/category/index',
    'pages/cart/index',
    'pages/checkin/index',
    'pages/user/index',
    'pages/constitution/intro',
    'pages/constitution/question',
    'pages/constitution/result',
    'pages/constitution/recommend',
    'pages/daily-health/list',
    'pages/daily-health/detail',
    'pages/course/list',
    'pages/course/detail',
    'pages/course/player',
    'pages/checkin/record',
    'pages/checkin/summary',
    'pages/product/list',
    'pages/product/detail',
    'pages/order/confirm',
    'pages/order/list',
    'pages/order/detail',
    'pages/order/aftersale',
    'pages/order/logistics',
    'pages/city/index',
    'pages/city/stores',
    'pages/city/store-detail',
    'pages/city/salon',
    'pages/city/group-buy',
    'pages/user/member',
    'pages/user/points',
    'pages/user/coupons',
    'pages/user/constitution-reports',
    'pages/user/checkin-history',
    'pages/user/address',
    'pages/user/address/edit',
    'pages/user/customer-service',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '毕生优养',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f8f8f8',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#EAA78B',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/index/index', text: '首页', iconPath: 'assets/images/tab-home.png', selectedIconPath: 'assets/images/tab-home-active.png' },
      { pagePath: 'pages/category/index', text: '分类', iconPath: 'assets/images/tab-category.png', selectedIconPath: 'assets/images/tab-category-active.png' },
      { pagePath: 'pages/cart/index', text: '购物车', iconPath: 'assets/images/tab-cart.png', selectedIconPath: 'assets/images/tab-cart-active.png' },
      { pagePath: 'pages/checkin/index', text: '打卡', iconPath: 'assets/images/tab-checkin.png', selectedIconPath: 'assets/images/tab-checkin-active.png' },
      { pagePath: 'pages/user/index', text: '我的', iconPath: 'assets/images/tab-user.png', selectedIconPath: 'assets/images/tab-user-active.png' },
    ],
  },
  permission: {
    'scope.userLocation': { desc: '用于门店地图定位功能' },
  },
  lazyCodeLoading: 'requiredComponents',
}
